ilive_common:
   if_dump_log: 0                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 1            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.01           # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1        # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 0        # If enable estimate the extrinsic between camera and IMU. [default = 1]
   estimate_intrinsic: 0            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1] 
   maximum_vio_tracked_pts: 600     # The maximum points for tracking. [default = 600]
   append_global_map_point_step: 4  # The point step of append point to global map. [default = 4]
   # gravity: [ -0.00668 ,0.1318004, -9.8038]       # Gravity      #d  (取IMU數據第一幀)
   gravity: [ 0.0, 0.0, 9.80416]
   esikf_iter_f2f_times: 1
   esikf_iter_f2map_times: 2
   use_lio: 1
   use_vio_f2f: 0
   use_vio_f2map: 0
   use_consistent_solution: true    
   if_save_mapping: false
   method: "InEKF"                         #EKF,InEKF,EIKF

#  0.0324   -0.0131    0.9994    0.1717
#    -0.9993    0.0157    0.0326    0.0174
#    -0.0161   -0.9998   -0.0126    0.2347
#          0         0         0    1.0000
# fisheye
ilive_vio:
   image_width:  2448 #dd
   image_height: 2048 #dd
   camera_intrinsic:                             #dd
      [1308.1691840205795,  0,           1221.8790961896898,
      0.0,          1318.683585974909,   1052.024852216732,
      0.0,          0.0,         1.0       ] 
   camera_dist_coeffs: [-0.13274940732954246, 0.3435168982763474, 0.007927480590485703, -0.00010939869901162644, 0] #dd #k1, k2, p1, p2, k3
      # <imu to cam1>
   camera_ext_R:                                #dd
         # [0.0324,   -0.0131    ,0.9994 ,
         #   -0.9993    ,0.0157   , 0.0326 ,
         #        -0.0161  , -0.9998 ,  -0.0126]
          [1,0,0,0,1,0,0,0,1]
   camera_ext_t: [   0.1717,  0.0174,  0.2347]      #d
   cam_cov_scale: 0.001


Lidar_front_end:
   lidar_type: 2   # 0 for mid, 1- Livox-horizon, 2 for velodyne 16, ，3 for Ouster   #d
   N_SCANS: 32                           #d
   using_raw_point: 1
   point_step: 1
   lid_cov_scale: 0.00015                                 

ilive_lio:        
   lio_update_point_step: 4   # Point step used for LIO update.
   max_iteration: 2         # Maximum times of LIO esikf. The number of the iterative steps.//1.2.3
   lidar_time_delay: 0.0   #d       # The time-offset between LiDAR and IMU, provided by user. 
   filter_size_corner: 0.50   
   filter_size_surf: 0.50
   filter_size_surf_z: 0.50
   filter_size_map: 0.50
   ext_t_lid_in_imu: [0, 0,-0.28]   #dd
   ext_R_lid_in_imu:                            #dd
            #   [    0, -1,  0 ,
            #         1,  0,  0 , 
            #        0,  0,  1]
            [1,0,0,0,1,0,0,0,1]

   publish_feature_map: true  
   long_rang_pt_dis: 1000             
   planar_check_dis: 0.15                                                                           

# The same as SR LIO 
ilive_IMU:
   imu_cov_scale: 0.0001
   max_IMU_calibration_num: 100
   COV_ACC_NOISE_DIAG:  0.01    #dd
   COV_OMEGA_NOISE_DIAG: 0.01    #dd
   COV_BIAS_ACC_NOISE_DIAG: 0.0001          #dd
   COV_BIAS_GYRO_NOISE_DIAG: 0.0001        #dd